targets:
  $default:
    builders:
      json_serializable:
        options:
          # https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
          explicit_to_json: true
